# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  prepare-env:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Preparing environment
        run: |
          pwd
          ls -lFsa
          sudo apt install gcc
          sudo apt install build-essential
          
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Builds a binary
        run: |
          cd Algorithms_TSP_ILS/
          make
          ls -lFsa
#          g++ -std=c++17 Algorithms_TSP_ILS/Point.h Algorithms_TSP_ILS/GCycle.h Algorithms_TSP_ILS/main.cpp -o main -O3 -Ofast -Os;
      - name: 'Upload Artifact (executable)'
        uses: actions/upload-artifact@v2
        with:
          path: "Algorithms_TSP_ILS/main"
          retention-days: 7
      - name: Telegram send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO_DEBUG }}
          token: ${{ secrets.TELEGRAM_TOKEN_DEBUG }}
          args: Hello world ${{ github.event_name }}
          document: Algorithms_TSP_ILS/main
  
